project_id = "bpnripefhggcfvgcljeg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[edge_functions]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
file_size_limit = "50MiB"

[auth.email]

[analytics]
enabled = false

[dashboard]
enabled = false

[functions.n8n-whatsapp-sync]
verify_jwt = false